VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsProject"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' 프로젝트 클래스

Private sizeOfVariables   As Integer ' 변수들의 크기
Public prjNum             As Integer  
Public periods            As Integer
Public ActivityCnt        As Integer
Public Activity1          As Integer
Public Activity2          As Integer
Public Activity3          As Integer
Public Activity4          As Integer
Public Activity5          As Integer
Public Activity6          As Integer

Public Sub Init()

End Sub

Sub Name()
  
End Sub

